### ISSUE TITLE
It stays on "Loading..." in a green box when i open the site.

### ISSUE THREAD

**Issue by Halkem3ds** [remixer-dec/YouTubePlaylistRandomizer#2]
![image_2023-09-23_155419738](https://github.com/remixer-dec/YouTubePlaylistRandomizer/assets/74405981/b549211f-4e4d-4ebe-a16c-d900753628bc)
I use Opera GX. If i randomize the playlist again works fine, but it doesn't load my previous seed and position sadly.

**Comment by remixer-dec** [comment]
Hi, thanks for reporting the issue, please check if it works correctly now.

**Comment by Halkem3ds** [comment]
It's working now! Thanks for the quick solution and for this project aswell, it's great to be able to listen to playlists like this!
